language: ruby

rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - jruby-19mode
  - jruby-20mode
  - rbx-19mode

gemfile:
  - gemfiles/activemodel3.gemfile
  - gemfiles/activemodel4.gemfile

matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: gemfiles/activemodel4.gemfile
